version: '3.8'
services:
  db:
    container_name: mysql_db
    image: mysql:9.2.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_TCP_PORT: ${DATABASE_PORT}
    ports:
      - '${DATABASE_PORT}:${DATABASE_PORT}'
    volumes:
      - db:/var/lib/mysql

  app:
    container_name: nestjs_app
    build:
      context: .
      dockerfile: DockerFile
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - '${NODE_PORT}:${NODE_PORT}'
    volumes:
      - .:/usr/src/app # Mount local code to container
      - /usr/src/app/node_modules # Prevent overwriting node_modules
    command: pnpm start:dev

volumes:
  db:
    driver: local
