# Use Node.js base image
FROM node:22-alpine

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy package files and install dependencies
COPY package.json pnpm-lock.yaml prisma ./
RUN corepack enable && pnpm install --frozen-lockfile

# Generate Prisma Client
RUN pnpm prisma generate

# Copy the rest of the application code
COPY . .

# Expose the application port
EXPOSE ${APP_PORT}

RUN pnpm build

# Command to start the app
CMD ["sh", "-c", "pnpm db:deploy && pnpm start:dev"]