# Use Node.js base image
FROM node:22-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy package files and install dependencies
COPY package.json pnpm-lock.yaml ./
RUN corepack enable && pnpm install --frozen-lockfile

# Generate Prisma Client
COPY prisma ./
RUN pnpm prisma generate

# Copy the rest of the application code
COPY . .

# Expose the application port
EXPOSE ${APP_PORT}

# Ensure Prisma migration runs before the app starts
CMD pnpm db:deploy && pnpm start:dev