version: '3.8'
services:
  db:
    container_name: mysql_db
    image: mysql:9.2.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_TCP_PORT: ${DATABASE_PORT}
    ports:
      - '${DATABASE_PORT}:${DATABASE_PORT}'
    healthcheck:
      test:
        [
          'CMD',
          'mysqladmin',
          'ping',
          '-h',
          'localhost',
          '-u',
          'root',
          '-p$$DATABASE_ROOT_PASSWORD',
        ]
      timeout: 20s
      retries: 10
    volumes:
      - db:/var/lib/mysql

  app:
    container_name: nestjs_app
    build:
      context: .
      dockerfile: DockerFile
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - DATABASE_HOST=mysql_db
      - DATABASE_URL=mysql://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@mysql_db:${DATABASE_PORT}/${DATABASE_NAME}
    ports:
      - '${NODE_PORT}:${NODE_PORT}'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:${NODE_PORT}/health']
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - .:/usr/src/app # Mount local files into the container
      - /usr/src/app/node_modules # Prevent overwriting node_modules

volumes:
  db:
    driver: local
