version: '3.8'
services:
  db:
    image: mysql:9.2
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - '${DATABASE_PORT}:3306'
    volumes:
      - db:/var/lib/mysql
volumes:
  db:
    driver: local
